### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zarevskaya** [seguinleo/Bloc-notes#5]
Hello,

I just discovered your app, it's really nice!

If I understood correctly, you need https to be able to save the notes?

Without HTTPS I get an error when I want to save a note.

Bonne journée.

**Comment by seguinleo** [comment]
Hello,

HTTPs is not required. What type of error do you have? Local or cloud? Do you use Docker? Sometimes this is caused by CSRF protection when the connection timed out, a simple reload solves the problem.

**Comment by zarevskaya** [comment]
I use Docker in local, for the moment.
No logs for this error. 

![Screenshot_20240418_002717](https://github.com/seguinleo/Bloc-notes/assets/60230221/ac584a8d-7c7d-4bf4-8fcd-28c87407493c)

**Comment by seguinleo** [comment]
Ok, I push few cookie fixes. The website is available at localhost:80, but if you want to deploy it on a server with a custom domain name or an IP address, you need to install a SSL certificate to use note encryption (Web Crypto API requires HTTPs for non localhost).

**Comment by zarevskaya** [comment]
I now understand why I was having this little problem.

Thank you for your responsiveness 👍
