### ISSUE TITLE
Markdown checkboxes

### ISSUE THREAD

**Issue by ahauck176** [seguinleo/Bloc-notes#8]
When adding check boxes using markdown it doesn't allow clicking the textbox to check it, I'm not sure if this is a feature request or a bug, but I'm filing it under feature request since other markdown note apps support this. (jk, i've never filed an issue before and i cannot figure out how to add a label, my bad)

**Comment by seguinleo** [comment]
Hi, yes I already thought about it, for the moment I have deactivated the checkboxes so it is normal that we cannot modify them. Maybe I'll add this feature in a future update...
